name: Prettify & Lint

on:
  pull_request:

jobs:
  lint:
    name: Prettify & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Download dependencies
        run: pnpm install
      - name: Run Prettier
        run: pnpm run prettier
      - name: Run ESLint
        run: pnpm run lint
